In [9]:
i=1 #변수i 에 1할당

In [10]:
 while i < 5: #i가 5보다 작을 때까지 반복
    i+=1      # i = i+1이랑 같은 의미
    print(i)  # i출력

2
3
4
5

In [4]:
i=0                #반복 카운터, 초기화 
sum=0              #누적할 변수, 초기화
while i <100 :     #0부터 100까지 실행,만일 실행횟수는 100회 
    i+=1           #i=0+1, i=1+1, i=2+1, i=3+1,i는 1씩 증가 
    sum = sum + i  #sum=0+1, sum=1+2, sum=3+3,sum=6+4 ...
                   #sum은 더한 값이 누적됨
print("sum=",sum)  #while 반복을 빠져 나와서 출력
#이 코드는 1부터 100까지의 합

sum= 5050

In [7]:
i=0 #반복 카운터, 초기화             
sum=0 #누적할 변수, 초기화
while i <100 : #0부터 100까지 실행,만일 실행횟수는 100회 
    sum = sum + i #sum=0+1, sum=1+2, sum=3+3,sum=6+4 ...
                  #sum은 더한 값이 누적됨
    i+=1          #i=0+1, i=1+1, i=2+1, i=3+1,i는 1씩 증가 
print("sum=",sum) #while 반복을 빠져 나와서 출력
#이 코드는 0부터 99까지의 합

sum= 4950

In [8]:
i=0 #반복 카운터, 초기화  
sum=0 #누적할 변수, 초기화
while i <101 : #0부터 101까지 실행,만일 실행횟수는 101회 
    sum = sum + i #sum=0+1, sum=1+2, sum=3+3,sum=6+4 ...
                  #sum은 더한 값이 누적됨
    i+=1 #i=0+1, i=1+1, i=2+1, i=3+1,i는 1씩 증가          
print("sum=",sum)#while 반복을 빠져 나와서 출력
#이 코드는 0부터 100까지의 합

sum= 5050

In [11]:
i=0 #i를 0으로 초기화

In [12]:
for a in ["1",2,"3",55]: 
# for 루프를 사용하여 리스트 ["1", 2, "3", 55]의 각 항목을 반복적으로 처리
    print("a[",i,"] 자료형:",type(a)," 값:",a) 
    #print() 함수는 각 항목의 인덱스를 출력하고, 해당 항목의 자료형과 값도 함께 출력
    i+=1
    #i = i+1과 같은 의미

a[ 0 ] 자료형: <class 'str'>  값: 1
a[ 1 ] 자료형: <class 'int'>  값: 2
a[ 2 ] 자료형: <class 'str'>  값: 3
a[ 3 ] 자료형: <class 'int'>  값: 55

In [13]:
for i in range(1,10,1): 
#변수 i가 1부터 10까지 1씩 증가하면서 반복
    print(i,",",end="")
    #i 변수에 저장된 값을 쉼표로 구분하여 출력하는 코드
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,

In [14]:
for i in range(10): 
# 0부터 9까지의 정수를 변수 i에 하나씩 대입하며 반복문 내부의 코드를 실행
    print(i,",",end="")
    #print() 함수를 이용해 i 값과 ,를 출력하고, 
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

0 ,1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,

In [15]:
for i in range(1,10):
#1부터 9까지의 정수를 변수 i에 하나씩 대입하며 반복문 내부의 코드를 실행
    print(i,",",end="")
     #print() 함수를 이용해 i 값과 ,를 출력하고, 
     #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

1 ,2 ,3 ,4 ,5 ,6 ,7 ,8 ,9 ,

In [16]:
for i in range(1,10,2): 
#1부터 9까지 2씩 증가시키면서 반복
    print(i,",",end="")
    #print() 함수를 이용해 i 값과 ,를 출력하고, 
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

1 ,3 ,5 ,7 ,9 ,

In [17]:
for i in range(10,0,-1): 
#10부터 0까지 -1씩 감소시키면서 반복
    print(i,",",end="")
    #print() 함수를 이용해 i 값과 ,를 출력하고, 
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

10 ,9 ,8 ,7 ,6 ,5 ,4 ,3 ,2 ,1 ,

In [18]:
for i in range(10): 
# 0부터 9까지의 정수를 변수 i에 하나씩 대입하며 반복문 내부의 코드를 실행
    if(i==3):
    #i 가 3이면
        break #해당 루프를 탈출
    print(i,",",end="")
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

0 ,1 ,2 ,

In [19]:
for i in range(10): 
# 0부터 9까지의 정수를 변수 i에 하나씩 대입하며 반복문 내부의 코드를 실행
    if(i==3):
    #i 가 3이면
        continue #문장 아래를 실행하지 않고 반복문의 처음으로 이동 후 계속 반복수행
    print(i,",",end="")
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정

0 ,1 ,2 ,4 ,5 ,6 ,7 ,8 ,9 ,

In [20]:
i=0;sum=0 #i와 sum을 0으로 초기화

In [21]:
while True:#무한루프 실행
    i+=1;sum+=i 
    #i =i +1과 같은 의미 ; sum = sum+i와 같은 의미 (누적합)
    if(i==100): break
    #만약 i가 100이라면 해당 루프 탈출

In [22]:
print("i=",i,"sum=",sum)# i와 sum 출력

i= 100 sum= 5050

In [24]:
 for i in range(1,121):
#1부터 121까지의 정수를 변수 i에 하나씩 대입하며 반복문 내부의 코드를 실행 
    print("*",end="")
    #print() 함수를 이용해 *를 출력하고
    #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정
    if(i%30==0): print(end="\n")
    #i를 30으로 나눈 나머지가 0이라면 개행

******************************
******************************
******************************
******************************

In [25]:
#구구단 출력
for i in range(1,10):
#for문에서는 1부터 9까지의 숫자 범위를 i 변수에 대입
    for j in range(1,10):
    # for문에서는 1부터 9까지의 숫자 범위를 j 변수에 대입
        print( i,"*",j,"=",i*j) 
        #각각의 숫자 i와 j를 곱한 값을 출력
    print("********************")
    #구분선을 출력

1 * 1 = 1
1 * 2 = 2
1 * 3 = 3
1 * 4 = 4
1 * 5 = 5
1 * 6 = 6
1 * 7 = 7
1 * 8 = 8
1 * 9 = 9
********************
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
********************
3 * 1 = 3
3 * 2 = 6
3 * 3 = 9
3 * 4 = 12
3 * 5 = 15
3 * 6 = 18
3 * 7 = 21
3 * 8 = 24
3 * 9 = 27
********************
4 * 1 = 4
4 * 2 = 8
4 * 3 = 12
4 * 4 = 16
4 * 5 = 20
4 * 6 = 24
4 * 7 = 28
4 * 8 = 32
4 * 9 = 36
********************
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
********************
6 * 1 = 6
6 * 2 = 12
6 * 3 = 18
6 * 4 = 24
6 * 5 = 30
6 * 6 = 36
6 * 7 = 42
6 * 8 = 48
6 * 9 = 54
********************
7 * 1 = 7
7 * 2 = 14
7 * 3 = 21
7 * 4 = 28
7 * 5 = 35
7 * 6 = 42
7 * 7 = 49
7 * 8 = 56
7 * 9 = 63
********************
8 * 1 = 8
8 * 2 = 16
8 * 3 = 24
8 * 4 = 32
8 * 5 = 40
8 * 6 = 48
8 * 7 = 56
8 * 8 = 64
8 * 9 = 72
********************
9 * 1 = 9
9 * 2 = 18
9 * 3 = 27
9 * 4 = 36
9 * 5 = 45
9 * 6 = 54
9 * 7 = 63
9 * 8 = 72
9 * 9 = 81
********************

In [26]:
for i in range(1,10):
#for문에서는 1부터 9까지의 숫자 범위를 i 변수에 대입
    for j in range(i,10):
    # for문에서는 1부터 9까지의 숫자 범위를 j 변수에 대입
        print( "*",end="")
        #print() 함수를 이용해 *를 출력하고
        #end=""를 지정해주어 개행 대신에 빈 문자열을 출력하도록 설정
    print(end="\n")
    #줄바꿈

*********
********
*******
******
*****
****
***
**
*

In [27]:
i=1 # i값을 1로 초기화합니다
while True: # 무한 루프를 실행
    j=i #: j값을 i와 같게 초기화
    while True: # 무한 루프를 실행
        if(j==10): break
        #j값이 10이 되면 안쪽 while 루프를 빠져나옴
        print( "*",end="") 
        #별(*)을 출력하고 다음 출력을 이어서 하기 위해 end 옵션에 ""을 지정
        j+=1 #: j값을 1 증가 
    if(i==10): break 
     #i값이 10이 되면 바깥쪽 while 루프를 빠져나옵니다
    print(end="\n") 
    #줄 바꿈
    i+=1
    #i값을 1 증가

*********
********
*******
******
*****
****
***
**
*

In [33]:
Mon=1 #Mon을 1로 초기화
for LastDay in [31,28,31,30,31,30,31,31,30,31,30,31]:
#리스트 [31,28,31,30,31,30,31,31,30,31,30,31]를 순회하며 LastDay 변수에 하나씩 할당
    print(Mon,"월 :",end="")
    #현재 월과 :를 출력합니다. end=""는 출력 후 줄바꿈을 하지 않도록 함
    for Day in range(1,LastDay+1):
    #1부터 LastDay+1까지의 범위에서 Day 변수를 순회
        print(Day,end=",") 
        #Day 값을 출력하고 ,로 구분합니다. end=""는 줄바꿈을 하지 않도록 함.
    print(end="\n") #줄바꿈
    Mon+=1 #다음 달로 넘어가기 위해 Mon 값을 1 증가

1 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
2 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,
3 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
4 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
5 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
6 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
7 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
8 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
9 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
10 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,
11 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,
12 월 :1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,

In [31]:
for i in range(2,10,3): # 2단~9단 중 3 간격으로 반복
    for j in range(2,10): # 2~9까지 j 값 반복
        print(i,"*",j,"=",i*j,end="\t") # 구구단 출력한뒤 탭
        print(i+1,"*",j,"=",i*j,end="\t") # 구구단 출력한뒤 탭
        if(i+2!=10): print(i+2,"*",j,"=",i*j,end="\n") 
        ## 3단을 출력하는 경우 ; 구구단 출력한 뒤 탭
        else: print(end="\n")
        # 9*9 구구단 출력 후 개행
    print(end="\n")
    #한 단이 끝나면 다음 줄로 이동

2 * 2 = 4	3 * 2 = 4	4 * 2 = 4
2 * 3 = 6	3 * 3 = 6	4 * 3 = 6
2 * 4 = 8	3 * 4 = 8	4 * 4 = 8
2 * 5 = 10	3 * 5 = 10	4 * 5 = 10
2 * 6 = 12	3 * 6 = 12	4 * 6 = 12
2 * 7 = 14	3 * 7 = 14	4 * 7 = 14
2 * 8 = 16	3 * 8 = 16	4 * 8 = 16
2 * 9 = 18	3 * 9 = 18	4 * 9 = 18

5 * 2 = 10	6 * 2 = 10	7 * 2 = 10
5 * 3 = 15	6 * 3 = 15	7 * 3 = 15
5 * 4 = 20	6 * 4 = 20	7 * 4 = 20
5 * 5 = 25	6 * 5 = 25	7 * 5 = 25
5 * 6 = 30	6 * 6 = 30	7 * 6 = 30
5 * 7 = 35	6 * 7 = 35	7 * 7 = 35
5 * 8 = 40	6 * 8 = 40	7 * 8 = 40
5 * 9 = 45	6 * 9 = 45	7 * 9 = 45

8 * 2 = 16	9 * 2 = 16
8 * 3 = 24	9 * 3 = 24
8 * 4 = 32	9 * 4 = 32
8 * 5 = 40	9 * 5 = 40
8 * 6 = 48	9 * 6 = 48
8 * 7 = 56	9 * 7 = 56
8 * 8 = 64	9 * 8 = 64
8 * 9 = 72	9 * 9 = 72

In [32]:
for i in range(2,5): # 2에서 4까지 반복하는 i 변수의 for 루프
    for j in range(2,10): #2에서 9까지 반복하는 j 변수의 for 루프
        print(i,"*",j,"=",i*j,end="\t") # i와 j를 곱한 값을 출력하고, 탭으로 분리
        print(i+3,"*",j,"=",i*j,end="\t")# i+3과 j를 곱한 값을 출력하고, 탭으로 분리
        if(i+6!=10): print(i+6,"*",j,"=",i*j,end="\n") 
        # i+6과 j를 곱한 값을 출력하고, 개행
        else: print(end="\n")
        # i+6이 10이 아닐 때만 출력
    print(end="\n")
    #한 번 더 개행

2 * 2 = 4	5 * 2 = 4	8 * 2 = 4
2 * 3 = 6	5 * 3 = 6	8 * 3 = 6
2 * 4 = 8	5 * 4 = 8	8 * 4 = 8
2 * 5 = 10	5 * 5 = 10	8 * 5 = 10
2 * 6 = 12	5 * 6 = 12	8 * 6 = 12
2 * 7 = 14	5 * 7 = 14	8 * 7 = 14
2 * 8 = 16	5 * 8 = 16	8 * 8 = 16
2 * 9 = 18	5 * 9 = 18	8 * 9 = 18

3 * 2 = 6	6 * 2 = 6	9 * 2 = 6
3 * 3 = 9	6 * 3 = 9	9 * 3 = 9
3 * 4 = 12	6 * 4 = 12	9 * 4 = 12
3 * 5 = 15	6 * 5 = 15	9 * 5 = 15
3 * 6 = 18	6 * 6 = 18	9 * 6 = 18
3 * 7 = 21	6 * 7 = 21	9 * 7 = 21
3 * 8 = 24	6 * 8 = 24	9 * 8 = 24
3 * 9 = 27	6 * 9 = 27	9 * 9 = 27

4 * 2 = 8	7 * 2 = 8
4 * 3 = 12	7 * 3 = 12
4 * 4 = 16	7 * 4 = 16
4 * 5 = 20	7 * 5 = 20
4 * 6 = 24	7 * 6 = 24
4 * 7 = 28	7 * 7 = 28
4 * 8 = 32	7 * 8 = 32
4 * 9 = 36	7 * 9 = 36